name: Reciclus
favicon: null
layout_spectrum: 0.927044861484319
typography_spectrum: 0.851663472596556
title: Uma ideia transformadora
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee0546'
    - '#080607'
    - '#bcbcbc'
    - '#696969'
  brandStrength: 0.5329880337230861
  lightness: 0.2758044423535466
  saturation: 0.8897453751415014
  rhythmicContrast: 0.29574009263888
purpose: []
